In [18]:
# Scrapes information about UT professors from Ratemyprofessors

#Importing and assigning link, opening in chrome driver
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
import time

driver_path = './chromedriver.exe'
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(executable_path = driver_path, options = options)
url = 'https://www.ratemyprofessors.com/search/teachers?query=*&sid=1255'
driver.get(url)

#Closes cookie notification
time.sleep(3)
close_button = driver.find_element_by_class_name('CCPAModal__StyledCloseButton-sc-10x9kq-2')
close_button.click()

#Clicks on show more for a minute
run_time = 60
end_time = time.time() + run_time

while time.time() < end_time:
        time.sleep(0.5)
        show_more = driver.find_element_by_class_name('PaginationButton__StyledPaginationButton-txi1dr-1')
        show_more.click()

#Handing the page to beautifulsoup
page_source = driver.page_source

soup = BeautifulSoup(page_source, 'html.parser')

In [53]:
#Creating dataframe

import pandas as pd

headers = ['Name', 'Department', 'Would Take Again', 'Level of Difficulty', 'Rating', 'Number of Ratings']
rmp_df = pd.DataFrame(columns = headers)

teachers = soup.findAll('div', class_='TeacherCard__InfoRatingWrapper-syjs0d-3')
index = 0
for teacher in teachers:
    #Creating list to be appended to df
    info = []

    #Getting Name
    name = teachers[index].find('div', class_='CardName__StyledCardName-sc-1gyrgim-0')
    info.append(name.text)

    #Getting Deparment
    dpt = teachers[index].find('div', class_='CardSchool__Department-sc-19lmz2k-0')
    info.append(dpt.text)

    #Getting % that would take again and difficulty rating together
    wtaDiff = teachers[index].findAll('div', class_='CardFeedback__CardFeedbackNumber-lq6nix-2')
    info.append(wtaDiff[0].text)
    info.append(wtaDiff[1].text)

    #Getting Rating
    rating = teachers[index].find('div', class_='CardNumRating__CardNumRatingNumber-sc-17t4b9u-2')
    info.append(rating.text)

    #Getting number of ratings
    numRatings = teachers[index].find('div', class_='CardNumRating__CardNumRatingCount-sc-17t4b9u-3')
    info.append(numRatings.text)

    #Appending list to dataframe as a row
    rmp_df.loc[len(rmp_df)] = info
    index += 1

rmp_df

,Name,Department,Would Take Again,Level of Difficulty,Rating,Number of Ratings
0,Lynda Cleveland,Business,0%,3.2,2.6,24 ratings
1,James Pennebaker,Psychology,34%,2.9,4.1,39 ratings
2,Paul Hudson,Geography,N/A,4.1,3.8,9 ratings
3,James Enelow,Political Science,67%,3.1,2.9,57 ratings
4,William Doolittle,Geography,100%,3.4,4.8,17 ratings
...,...,...,...,...,...,...
707,Chris Ortiz&prentice,English,N/A,0,0.0,0 ratings
708,Nola Cottom,Nursing,N/A,0,0.0,0 ratings
709,Kara Kockelman,Engineering,0%,4,3.5,3 ratings
710,James Sidbury,History,N/A,0,0.0,0 ratings
711,Katy Branch,French & Italian,N/A,0,0.0,0 ratings